<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net6.0;net8.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="Shouldly" Version="4.2.1" />
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\src\Wyrm.CESIL\Wyrm.CESIL.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Examples\CesilProgram1.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Examples\CesilProgram1.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Examples\CesilProgram10.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Examples\CesilProgram10.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Examples\CesilProgram11.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Examples\CesilProgram11.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Examples\CesilProgram12.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Examples\CesilProgram12.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Examples\CesilProgram13.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Examples\CesilProgram13.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Examples\CesilProgram14.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Examples\CesilProgram14.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Examples\CesilProgram2.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Examples\CesilProgram2.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Examples\CesilProgram3.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Examples\CesilProgram3.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Examples\CesilProgram4.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Examples\CesilProgram4.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Examples\CesilProgram5.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Examples\CesilProgram5.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Examples\CesilProgram6.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Examples\CesilProgram6.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Examples\CesilProgram7.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Examples\CesilProgram7.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Examples\CesilProgram8.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Examples\CesilProgram8.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Examples\CesilProgram9.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Examples\CesilProgram9.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
